version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - sudo apt-get update
      - sudo apt-get install zip
      - pip install awscli
  build:
    commands:
      - echo "[+] Installing dependencies...."
      - pip install -r requirements.txt --target .
      - zip -r target-lambda.zip .
  post_build:
    commands:
      - echo Build completed
      - aws lambda update-function-code --function-name "$AWS_LAMBDA_NAME" --zip-file fileb://./target-lambda.zip
      - aws lambda publish-version --function-name "$AWS_LAMBDA_NAME"
artifacts:
  files:
    - '**/*'
  type: zip