version: 0.2
env:
  shell: bash
  variables:
    AWS_LAMBDA_NAME: "EmailSpamClassifier-SpamCheckLambda-V1bVUwfDXw82"
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt-get update
      - apt-get install zip
      - pip install awscli
  build:
    commands:
      - echo "[+] Installing dependencies...."
      - pip install -r requirements.txt --target .
      - zip -r target-lambda.zip .
  post_build:
    commands:
      - echo Build completed
      - aws lambda update-function-code --function-name "EmailSpamClassifier-SpamCheckLambda-V1bVUwfDXw82" --zip-file fileb://target-lambda.zip
      - aws lambda publish-version --function-name "EmailSpamClassifier-SpamCheckLambda-V1bVUwfDXw82"
artifacts:
  files:
    - '**/*'
  type: zip