version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo pwd
      - cd src/
      - echo "[+] Installing dependencies...."
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
  type: zip